name: ci
on:
  push:
    branches:
      - main
jobs:
  Dockerfile:
    env:
      file: Dockerfile
      pattern: {1: 0, 2: 80, 3: 805, 5: 4497, 4: 2790, 8: 4821, 7: 5759, 9: 3552, 6: 6246, 11: 1054, 10: 2082, 12: 558, 14: 140, 16: 70, 15: 90, 20: 6, 19: 14, 17: 44, 13: 250, 18: 20, 21: 8, 22: 4, 23: 0, 24: 0}
      registry: index.docker.io
      repository: santander-anagrams
      tagname: ci
      user: ganimedescolomar
      
    runs-on: ubuntu-18.04
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: docker build
        run: docker build --no-cache -t ${registry}/${user}/${repository}:${tagname} -f ${file} .
      -
        name: docker run
        run: docker run --detach --entrypoint python --name ${repository} -v ${PWD}/data:/data ${registry}/${user}/${repository}:${tagname} anagrams.py
      -
        name: docker logs
        run: |
                while true; do
                        sleep 10;
                        docker logs ${repository} 2>&1 | grep '${pattern}' && break
                done;
