name: ci
on:
  push:
    branches:
      - docker
jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: test
        run: docker build -t test .
      -
        name: docker run
        run: docker run --name test -v /data/words.txt:/data/words.txt test
